version: "3.9"

services:
  discord-bot:
    build: .
    container_name: shorts-downloader
    restart: unless-stopped
    volumes:
      - /srv/shorts-downloader/data:/app/data
      - /srv/shorts-downloader/bin:/app/bin
    tty: true 
    environment:
      - TOKEN=${TOKEN}