version: "3.9"

services:
  discord-bot:
    build: .
    container_name: shorts-downloader
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/srv/shorts-downloader/data
      - ./bin:/srv/shorts-downloader/bin
    tty: true